# This is a basic workflow to help you get started with Actions

name: Context

# Controls when the action will run. 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    	- name: "context"
			  run: echo "commit id => $COMMIT_ID"
      	env:
        	COMMIT_ID: ${{ github.sha }}

